# Generated by Django 5.0.14 on 2026-06-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sitesettings_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Загруженное изображение имеет приоритет над старым путём.', null=True, upload_to='projects/', verbose_name='Превью (загрузить)'),
        ),
        migrations.CreateModel(
            name='ProjectScreenshotTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10, verbose_name='Язык')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('screenshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portfolio.projectscreenshot', verbose_name='Скриншот')),
            ],
            options={
                'verbose_name': 'Перевод скриншота',
                'verbose_name_plural': 'Переводы скриншотов',
                'unique_together': {('screenshot', 'language')},
            },
        ),
    ]
